#!/usr/bin/env python3
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license
import argparse
from glob import glob
import pandas as pd

parser = argparse.ArgumentParser()
parser.add_argument('--start')
parser.add_argument('--end')
parser.add_argument('--periods', type=int)
args = parser.parse_args()

dtype = {'node_id': str}
df = pd.concat(pd.read_csv(path, dtype=dtype)
               for path in glob('/storage/projects/*/nodes.csv'))

nodes = set(df.node_id)

dates = set(pd.date_range(start=args.start,
                          end=args.end, periods=args.periods).date)

for node in nodes:
    for date in dates:
        node = node.rjust(16, '0')
        print(node, date)
